### ISSUE TITLE
Ошибка при создании паблишера в классе Mela

### ISSUE THREAD

**Issue by zloy-zhake** [uthunderbird/mela#1]
При создании паблишера с именем "default" метод publisher() из класса Mela пытается взять настройки из self.config['publisher'] (строка 107 тут: https://github.com/alem-research/mela/blob/main/mela/__init__.py)
Но в self.config нет ключа 'publisher'. Есть:

['services']['service-name']['publisher']
['services.service-name']['publisher']
['services.service-name.publisher']

Просто ['publisher'] нет.

Шаги для вопросизводства:
```
>>> from mela import Mela
>>> app = Mela("test")
>>> app.configure_from_yaml('application.yml')
>>> from pprint import pprint
>>> pprint(app.config)
```

**Comment by uthunderbird** [comment]
Задача, на самом деле, сводится к документации. Добавил пример сервиса, который помимо базовой обработки сообщений, будет ещё иметь один дополнительный паблишер, в который также можно публиковать сообщения.

Посмотреть можно [тут](https://github.com/alem-research/mela/tree/main/examples/extra_publishing_service).
