### ISSUE TITLE
Integration request

### ISSUE THREAD

**Issue by Lancetnik** [uthunderbird/mela#12]
Hi, @uthunderbird ! I found you [habr article](https://habr.com/ru/articles/737134/). You create a really interesting project.
But, anfortunatelly, I have a [same one](https://github.com/Lancetnik/Propan) and it goes deeper as I can see. So, if you steel interested in *messaging projects*, maybe you wanna join to **Propan** as a contributor?

**Comment by uthunderbird** [comment]
Hello! Let's make a call to discuss our visions. I think it would be great
if we find common points and decide to go forward together.

пн, 3 июл. 2023 г., 01:58 Pastukhov Nikita ***@***.***>:

**Comment by uthunderbird** [comment]
You can reach me by telegram account @underbird
